language: python
python:
  - "2.7"
  - "3.7"
install:
  - pip install pipenv
  - pipenv install -e .[dev]
script:
  - pipenv run flake8 --max-line-length=100 . 
  - pipenv run pylint s3resumable
  - pipenv run coverage run --source=s3resumable -m pytest
  - pipenv run coverage report -m 
