language: python

python:
- '2.7'
- '3.7'

env:
- PIPENV_VERBOSITY=-1

install:
- pip install pipenv
- pipenv install -e .[dev]

script:
- pipenv run flake8 --max-line-length=100 .
- pipenv run pylint s3resumable
- pipenv run coverage run --source=s3resumable -m pytest
- pipenv run coverage report -m


jobs:
  include:
    - stage: deploy
      deploy:
        provider: pypi
        user: __token__
        password:
          secure: aSkULw3vj7JbLVKDXlTEZwdTYyd7PwAhTsswoYkg+cVkvN44bN4+hlgxr+/1qb0HZNQ4/QW6HNzxFM+Wv7+qqYBCg+tTfy5uPaH1vTA6hBL0aTyYDKsjP+wdugBGQaZ3WbLF85bAiTIaZdEU2vWrjotEeDr8vdFMNW6Z3nKe0o8QtdZUs6QOwGltNmH+5l8XjPRmoMa6knGyViowC6UY8Bj623Xq12+rmsy/Lq9NaLDPhRP2DB90UzISl8zfE+WtQs8OEg1J5Qg11ZG3/UGb1zduJf1973Rx8Vv1udRFtcMqGoadEiHsn7sJn2CdY18+YkC8tBlYn3uSiCxVrQu927iArd2X/jc2VuUQuHLUtsK8zSO2WrbnA26vWPNDtw2X4Gbkh2LPaLXcGAoY6exudN2AAbrQ/giZKQx3AUGZebZ0OPBsb2z2yYr0fD7glVhoI0fiPPNWMITG6ysPb4vEXIzUn5hg+yJON7gFMhqmPLP2zGBLPwV4z1M4KiDVQSppBSbvjc3KUkvWqRXK+pYcpvIevG5Pa/9GCpzmKzKNILAOpr58BpMrfvoH1wxcQVpE1KjXKQnZ5DWSkstXKJllQ5mEWTAu7rIy4FBGd+JWLOr9wX/xLCDkfYGjh6GS9N2jFH8uZQk1W1Wf+EWfcQ+dE3KYY9VXuEa6QljE0R3IgeA=
        on:
          tags: true
